package com.scamofty

import io.ktor.server.application.*
import io.ktor.server.engine.*
import io.ktor.server.netty.*
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

@Serializable
data class Note(
    val title: String,
    val content: String,
    val timestamp: Long,
    val color: Int,
    val id: Int? = null
)

@Serializable
data class CreateNoteRequest(
    val title: String,
    val content: String,
    val color: Int
)

fun main(args: Array<String>) {
    //Was originally in autogenerated code from ktor site but was causing issues running from Docker
    //io.ktor.server.netty.EngineMain.main(args)
    

    val port = System.getenv("PORT")?.toInt() ?: 8080
    val host = System.getenv("HOST") ?: "0.0.0.0"

    println("=== SERVER CONFIG ===")
    println("Host: $host")
    println("Port: $port")
    println("====================")

    println("Starting server on $host:$port")
    embeddedServer(Netty, port = port, host = host, module = Application::module){
        println("Mainframe booting...")
    }.start(wait = true)
}

fun Application.module() {
    configureRouting()
}
