package com.scamofty

import io.ktor.server.application.*
import io.ktor.server.engine.*
import io.ktor.server.netty.*


fun main(args: Array<String>) {
    //Was originally in autogenerated code but was causing issues running from Docker
    //io.ktor.server.netty.EngineMain.main(args)

    val port = System.getenv("PORT")?.toInt() ?: 8080
    val host = System.getenv("HOST") ?: "0.0.0.0"

    println("Starting server on $host:$port")
    embeddedServer(Netty, port = port, host = host, module = Application::module)
        .start(wait = true)
}

fun Application.module() {
    configureRouting()
}
